---
#
# Personnalisation du Site
# !!!Ne pas changer le nom et déplacer ce fichier
#
title : "FOIREXPO ST-MAIXENT"
subtitle: "du 9 au 12 avril 2021"

# l'image arrondie dans la carte du sommaire
avatar: "/site/avatar.jpg"

# l'icône dans l'onglet du navigateur
favicon: "/site/favicon.svg"

# l'image d'arrière plan du site
backgroundImage: "https://images.pexels.com/photos/4593407/pexels-photo-4593407.jpeg?cs=srgb&dl=pexels-robyn-w-4593407.jpg&fm=jpg"
---